spring:
  profiles: default
server:
  port: 8761
eureka:
  instance:
        hostname: http://localhost:8761/eureka/
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---

spring:
  profiles: indexer
  application:
    name: service_indexer
server:
  port: 8084
eureka:
  instance:
    hostname: app_service_indexer
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://app_service_searcher:8085/eureka/,http://app_store_inverted_index:8086/eureka/,http://app_store_original_data:8087/eureka/

---

spring:
  profiles: searcher
  application:
    name: service_searcher
server:
  port: 8085
eureka:
  instance:
    hostname: app_service_searcher
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://app_service_indexer:8084/eureka/,http://app_store_inverted_index:8086/eureka/,http://app_store_original_data:8087/eureka/

---

spring:
  profiles: store_invert
  application:
    name: store_inverted_index
server:
  port: 8086
eureka:
  instance:
    hostname: app_store_inverted_index
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://app_service_indexer:8084/eureka/,http://app_service_searcher:8085/eureka/,http://app_store_original_data:8087/eureka/

---

spring:
  profiles: store_original
  application:
    name: store_original_data
server:
  port: 8087
eureka:
  instance:
    hostname: app_store_original_data
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://app_service_indexer:8084/eureka/,http://app_service_searcher:8085/eureka/,http://app_store_inverted_index:8086/eureka/