spring:
  application:
    name: service_ribbon

server:
  port: 5555

# Configure for Ribbon:
#ping-server:
#  ribbon:
#    eureka:
#      enabled: false # Disable default ping
#    listOfServers: localhost:8001,localhost:8002,localhost:8003,localhost:8004
#    ServerListRefreshInterval: 15000
#
---

# Configure for Ribbon:
  ribbon:
    eureka:
      enabled: false
  service_ribbon:
    ribbon:
      listOfServers: localhost:9092,localhost:9999
      ServerListRefreshInterval: 15000


# -- Configure Discovery Client (Eureka Client):
eureka:
  instance:
    appname: service_ribbon
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://app_service_indexer:8084/eureka/
