spring:
  application:
    name: store_original_data
  data:
    mongodb:
      database: originaltext
      host: localhost
      port: 27017

server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://my-eureka-server.com:8761/eureka/


