spring:
  application:
    name: config_client
  cloud:
    config:
      label: latest

server:
  port: 8083


eureka:
  client:
    serviceUrl:
      defaultZone: http://my-eureka-server.com:8761/eureka/
